### PR TITLE
Quality of Life Improvements

### PR DESCRIPTION
**Pull request by Tinkerlad0**
Quality of Life Improvements

-Fixes issue 51
-RE: Issue 49

-Implements subtle feedback when submitting buttons or text fields. The relevant controls will flash green for a moment if an operation is successful or red if not. Let me know what you think, its just a pretty basic solution but I thought it subtle yet pleasing.

-Completed method Save to USB, however feel free to change it as its only my implementation and requires more user interaction than the original bash script. Also does not mount the drive at all like original script.

Bugs!!!!

Unfortunately when closing the JFileChooser in the Save to USB tab, the admin panel is pushed behind the main panel. Not sure at this point in time why that occurs....

### CODE REVIEW

**Comment by JarrahGos** [comment]
Most of it looks great. Especially the flash. (going to take a look at the running of it soon)

However, I think I have worked out the problem with the JFileChooser. It is written in swing, which will not interact with JavaFX properly. 

Take a look at http://docs.oracle.com/javase/8/javafx/api/javafx/stage/FileChooser.html for the FX version of the same class. Hopefully this will solve it. 

Also, be sure to run a pull before submitting a PR or to make things easier, I can just make you a collaborator here. Whichever you would prefer. There was some alterations I made to Settings and your compat class (mainly javadoc) which the auto merge would overwrite. 

Anyway, I'm going to merge this for now and see what I can do with moving the JFileChooser bit to FX as well as getting the changes to merge properly. 

Thanks mate.

**Comment by Tinkerlad0** [comment]
Ahh, I'm too used to using swing or OGL that I didnt even think that it may conflict. The DirectoryChooser also looks a lot more elegant than the JFileChooser. Another issue I found was that the JFileChooser didnt work well with registering 'clicks' when using a touch interface. Good thing its gone.

When you say make sure to pull before a PR, you mean a fetch from your repo then merge and commit yeah? I ran that about 2 mins before I submitted. If its ok with you then having write access would be a lot easier to integrate into my workflow than trying to manage multiple concurrent PRs.

Also sorry about the inefficient code in the database saving methods. Looking back I'm not sure what I was thinking....

**Comment by JarrahGos** [comment]
All good. all of that has been put in now. 

Yep, that's what I was thinking of. Never really been on the other side of git (not owning the repo)

You have write access now. Use it wisely (and may both of us remember to pull before changing anything...)

**Comment by jarrah-95** [comment]
All good. all of that has been put in now. 

Yep, that's what I was thinking of. Never really been on the other side of git (not owning the repo)


You have write access now. Use it wisely (and may both of us remember to pull before changing anything...)

**Pull request merged**
